paths: # TODO Hay más de un train y más de un test
  raw:
    train: "dataset/NER/MEDDOPROF/train/brat" # Carpeta que contiene los archivos de texto y anotaciones de train
    dev: "dataset/NER/MEDDOPROF/dev/brat" # Carpeta que contiene los archivos de texto y anotaciones de dev
    test: "dataset/NER/MEDDOPROF/test/brat" # Carpeta que contiene los archivos de texto y anotaciones de test
  processed:
    train: "dataset/NER/MEDDOPROF/processed/train/train.hf" # HF Dataset con los datos de train
    dev: "dataset/NER/MEDDOPROF/processed/dev/dev.hf" # HF Dataset con los datos de dev
    test: "dataset/NER/MEDDOPROF/processed/test/test.hf" # HF Dataset con los datos de test
  label_map: "dataset/NER/MEDDOPROF/label_map/label2id.json"
  results: "results/NER/MEDDOPROF/"
  model_dir: "models/NER/MEDDOPROF/"

wandb_project: "eriberta-ner-MEDDOPROF"

hyperparameters:
  batch_size: 8
  learning_rate: 2.0e-5
  weight_decay: 0.01