paths:
  raw:
    train: "datasets/NER/SympTEMIST/train/brat" # Carpeta que contiene los archivos de texto y anotaciones de train
    dev: "datasets/NER/SympTEMIST/dev/brat" # Carpeta que contiene los archivos de texto y anotaciones de dev
    test: "datasets/NER/SympTEMIST/test/brat" # Carpeta que contiene los archivos de texto y anotaciones de test
  processed:
    train: "datasets/NER/SympTEMIST/processed/train/train.hf" # HF Dataset con los datos de train
    dev: "datasets/NER/SympTEMIST/processed/dev/dev.hf" # HF Dataset con los datos de dev
    test: "datasets/NER/SympTEMIST/processed/test/test.hf" # HF Dataset con los datos de test
  label_map: "datasets/NER/SympTEMIST/label_map/label2id.json"
  results: "results/NER/SympTEMIST/"
  model_dir: "models/NER/SympTEMIST/"

model_name: "HiTZ/EriBERTa-base"

wandb_project: "eriberta-ner-SympTEMIST"

hyperparameters:
  batch_size: 8
  learning_rate: 7.5e-5
  weight_decay: 0.0