paths:
  raw:
    train: "datasets/NER/PharmacoNER/Full_Cases/train/" # Carpeta que contiene los archivos de texto y anotaciones de train
    dev: "datasets/NER/PharmacoNER/Full_Cases/dev/" # Carpeta que contiene los archivos de texto y anotaciones de dev
    test: "datasets/NER/PharmacoNER/Full_Cases/test/" # Carpeta que contiene los archivos de texto y anotaciones de test
  processed:
    train: "datasets/NER/PharmacoNER/Full_Cases/processed/train/train.hf" # HF Dataset con los datos de train
    dev: "datasets/NER/PharmacoNER/Full_Cases/processed/dev/dev.hf" # HF Dataset con los datos de dev
    test: "datasets/NER/PharmacoNER/Full_Cases/processed/test/test.hf" # HF Dataset con los datos de test
  label_map: "datasets/NER/PharmacoNER/Full_Cases/label_map/label2id.json"
  results: "results/NER/PharmacoNER/Full_Cases"
  model_dir: "models/NER/PharmacoNER/Full_Cases"

wandb_project: "eriberta-ner-PharmacoNER-Full_Cases"

hyperparameters:
  batch_size: 8
  learning_rate: 2.0e-5
  weight_decay: 0.01