paths:
  raw:
    train: "dataset/NER/PharmacoNER-Sentences/brat/train/" # Carpeta que contiene los archivos de texto y anotaciones de train
    dev: "dataset/NER/PharmacoNER-Sentences/brat/dev/" # Carpeta que contiene los archivos de texto y anotaciones de dev
    test: "dataset/NER/PharmacoNER-Sentences/brat/test/" # Carpeta que contiene los archivos de texto y anotaciones de test
  processed:
    train: "dataset/NER/PharmacoNER-Sentences/processed/train/train.hf" # HF Dataset con los datos de train
    dev: "dataset/NER/PharmacoNER-Sentences/processed/dev/dev.hf" # HF Dataset con los datos de dev
    test: "dataset/NER/PharmacoNER-Sentences/processed/test/test.hf" # HF Dataset con los datos de test
  label_map: "dataset/NER/PharmacoNER-Sentences/label_map/label2id.json"
  results: "results/NER/PharmacoNER-Sentences/"
  model_dir: "models/NER/PharmacoNER-Sentences/"

wandb_project: "eriberta-ner-PharmacoNER-Sentences"

hyperparameters:
  batch_size: 8
  learning_rate: 2.0e-5
  weight_decay: 0.01