paths:
  raw:
    train: "datasets/NER/MEDDOPROF/subtrack1-ner/train/brat" # Carpeta que contiene los archivos de texto y anotaciones de train
    dev: "datasets/NER/MEDDOPROF/subtrack1-ner/dev/brat" # Carpeta que contiene los archivos de texto y anotaciones de dev
    test: "datasets/NER/MEDDOPROF/subtrack1-ner/test/brat" # Carpeta que contiene los archivos de texto y anotaciones de test
  processed:
    train: "datasets/NER/MEDDOPROF/subtrack1-ner/processed/train/train.hf" # HF Dataset con los datos de train
    dev: "datasets/NER/MEDDOPROF/subtrack1-ner/processed/dev/dev.hf" # HF Dataset con los datos de dev
    test: "datasets/NER/MEDDOPROF/subtrack1-ner/processed/test/test.hf" # HF Dataset con los datos de test
  label_map: "datasets/NER/MEDDOPROF/subtrack1-ner/label_map/label2id.json"

models:
  eriberta:
    results: "results/eriberta/NER/MEDDOPROF/subtrack1-ner/"
    model_name: "HiTZ/EriBERTa-base"
    wandb_project: "eriberta-ner-MEDDOPROF-subtrack1-ner"
    hyperparameters:
      batch_size: 8
      learning_rate: 3.0e-5
      weight_decay: 0.3

  eriberta_private:
    results: "results/eriberta/private/MEDDOPROF/subtrack1-ner/"
    model_name: "eriberta_models/private/eriberta"
    wandb_project: "eriberta-private-MEDDOPROF-subtrack1-ner"
    hyperparameters:
      batch_size: 8
      learning_rate: 3.0e-5
      weight_decay: 0.3
      
  longformer:
    results: "results/eriberta_longformer/public/MEDDOPROF/subtrack1-ner/"
    model_name: "eriberta_models/public/EriBERTa_Free_longformer_1024_attn_2048_max_size"
    wandb_project: "eriberta_longformer-public-MEDDOPROF-subtrack1-ner"
    hyperparameters: # TODO
      batch_size: 8
      learning_rate: 1.0e-5
      weight_decay: 0.0

  bsc:
    results: "results/bsc/public/MEDDOPROF/subtrack1-ner/"
    model_name: "PlanTL-GOB-ES/bsc-bio-ehr-es"
    wandb_project: "bsc-public-MEDDOPROF-subtrack1-ner"
    hyperparameters:
      batch_size: 8
      learning_rate: 3.0e-5
      weight_decay: 0.01