paths:
  raw:
    train: "datasets/NER/MultiCardioNER/track2/es/train/brat" # Carpeta que contiene los archivos de texto y anotaciones de train
    dev: "datasets/NER/MultiCardioNER/track2/es/dev/brat" # Carpeta que contiene los archivos de texto y anotaciones de dev
    test: "datasets/NER/MultiCardioNER/track2/es/test/brat" # Carpeta que contiene los archivos de texto y anotaciones de test
  processed:
    train: "datasets/NER/MultiCardioNER/track2/es/processed/train/train.hf" # HF Dataset con los datos de train
    dev: "datasets/NER/MultiCardioNER/track2/es/processed/dev/dev.hf" # HF Dataset con los datos de dev
    test: "datasets/NER/MultiCardioNER/track2/es/processed/test/test.hf" # HF Dataset con los datos de test
  label_map: "datasets/NER/MultiCardioNER/track2/es/label_map/label2id.json"
  results: "results/NER/MultiCardioNER/track2/es/"
  model_dir: "models/NER/MultiCardioNER/track2/es/"

wandb_project: "eriberta-ner-MultiCardioNER-track2"

hyperparameters:
  batch_size: 8
  learning_rate: 2.0e-5
  weight_decay: 0.01