paths:
  raw:
    train: "datasets/NER/PharmacoNER/Sentences/train/brat" # Carpeta que contiene los archivos de texto y anotaciones de train
    dev: "datasets/NER/PharmacoNER/Sentences/dev/brat" # Carpeta que contiene los archivos de texto y anotaciones de dev
    test: "datasets/NER/PharmacoNER/Sentences/test/brat" # Carpeta que contiene los archivos de texto y anotaciones de test
  processed:
    train: "datasets/NER/PharmacoNER/Sentences/processed/train/train.hf" # HF Dataset con los datos de train
    dev: "datasets/NER/PharmacoNER/Sentences/processed/dev/dev.hf" # HF Dataset con los datos de dev
    test: "datasets/NER/PharmacoNER/Sentences/processed/test/test.hf" # HF Dataset con los datos de test
  label_map: "datasets/NER/PharmacoNER/Sentences/label_map/label2id.json"
  results: "results/NER/PharmacoNER/Sentences/"
  model_dir: "models/NER/PharmacoNER/Sentences/"

wandb_project: "eriberta-ner-PharmacoNER-Sentences"

hyperparameters:
  batch_size: 8
  learning_rate: 2.0e-5
  weight_decay: 0.01