paths: # TODO No hay dev
  raw:
    train: "dataset/NER/DisTEMIST/train/brat" # Carpeta que contiene los archivos de texto y anotaciones de train
    dev: "dataset/NER/DisTEMIST/dev/brat" # Carpeta que contiene los archivos de texto y anotaciones de dev
    test: "dataset/NER/DisTEMIST/test/brat" # Carpeta que contiene los archivos de texto y anotaciones de test
  processed:
    train: "dataset/NER/DisTEMIST/processed/train/train.hf" # HF Dataset con los datos de train
    dev: "dataset/NER/DisTEMIST/processed/dev/dev.hf" # HF Dataset con los datos de dev
    test: "dataset/NER/DisTEMIST/processed/test/test.hf" # HF Dataset con los datos de test
  label_map: "dataset/NER/DisTEMIST/label_map/label2id.json"
  results: "results/NER/DisTEMIST/"
  model_dir: "models/NER/DisTEMIST/"

wandb_project: "eriberta-ner-DisTEMIST"

hyperparameters:
  batch_size: 8
  learning_rate: 2.0e-5
  weight_decay: 0.01