paths:
  raw:
    train: "datasets/NER/MEDDOCAN/train/brat" # Carpeta que contiene los archivos de texto y anotaciones de train
    dev: "datasets/NER/MEDDOCAN/dev/brat" # Carpeta que contiene los archivos de texto y anotaciones de dev
    test: "datasets/NER/MEDDOCAN/test/brat" # Carpeta que contiene los archivos de texto y anotaciones de test
  processed:
    train: "datasets/NER/MEDDOCAN/processed/train/train.hf" # HF Dataset con los datos de train
    dev: "datasets/NER/MEDDOCAN/processed/dev/dev.hf" # HF Dataset con los datos de dev
    test: "datasets/NER/MEDDOCAN/processed/test/test.hf" # HF Dataset con los datos de test
  label_map: "datasets/NER/MEDDOCAN/label_map/label2id.json"

models:
  eriberta:
    results: "results/eriberta/NER/MEDDOCAN/"
    model_name: "HiTZ/EriBERTa-base"
    wandb_project: "eriberta-ner-MEDDOCAN"
    hyperparameters:
      batch_size: 8
      learning_rate: 5.0e-5
      weight_decay: 0.01

  eriberta_private:
    results: "results/eriberta/private/MEDDOCAN/"
    model_name: "eriberta_models/private/eriberta"
    wandb_project: "eriberta-private-MEDDOCAN"
    hyperparameters:
      batch_size: 8
      learning_rate: 5.0e-5
      weight_decay: 0.01
      
  longformer:
    results: "results/eriberta_longformer/public/MEDDOCAN/"
    model_name: "eriberta_models/public/EriBERTa_Free_longformer_1024_attn_2048_max_size"
    wandb_project: "eriberta_longformer-public-MEDDOCAN"
    hyperparameters: # TODO
      batch_size: 8
      learning_rate: 1.0e-5
      weight_decay: 0.0

  bsc:
    results: "results/bsc/public/MEDDOCAN/"
    model_name: "PlanTL-GOB-ES/bsc-bio-ehr-es"
    wandb_project: "bsc-public-MEDDOCAN"
    hyperparameters:
      batch_size: 8
      learning_rate: 5.0e-5
      weight_decay: 0.2

  clin_x_es:
    results: "results/clin_x_es/public/MEDDOCAN/"
    model_name: "llange/xlm-roberta-large-spanish-clinical"
    wandb_project: "clin_x_es-public-MEDDOCAN"
    hyperparameters: # TODO
      batch_size: 8
      learning_rate: 1.0e-5
      weight_decay: 0.0

  mdeberta:
    results: "results/mdeberta/public/MEDDOCAN/"
    model_name: "microsoft/mdeberta-v3-base"
    wandb_project: "mdeberta-public-MEDDOCAN"
    hyperparameters:
      batch_size: 8
      learning_rate: 5.0e-5
      weight_decay: 0.0