paths:
  raw:
    train: "dataset/NER/MEDDOCAN/train/brat" # Carpeta que contiene los archivos de texto y anotaciones de train
    dev: "dataset/NER/MEDDOCAN/dev/brat" # Carpeta que contiene los archivos de texto y anotaciones de dev
    test: "dataset/NER/MEDDOCAN/test/brat" # Carpeta que contiene los archivos de texto y anotaciones de test
  processed:
    train: "dataset/NER/MEDDOCAN/processed/train/train.hf" # HF Dataset con los datos de train
    dev: "dataset/NER/MEDDOCAN/processed/dev/dev.hf" # HF Dataset con los datos de dev
    test: "dataset/NER/MEDDOCAN/processed/test/test.hf" # HF Dataset con los datos de test
  label_map: "dataset/NER/MEDDOCAN/label_map/label2id.json"
  results: "results/NER/MEDDOCAN/"
  model_dir: "models/NER/MEDDOCAN/"

wandb_project: "eriberta-ner-MEDDOCAN"

hyperparameters:
  batch_size: 8
  learning_rate: 2.0e-5
  weight_decay: 0.01