paths: # TODO No hay dev
  raw:
    train: "dataset/NER/SympTEMIST/train/brat/brat" # Carpeta que contiene los archivos de texto y anotaciones de train
    dev: "dataset/NER/SympTEMIST/dev/brat" # Carpeta que contiene los archivos de texto y anotaciones de dev
    test: "dataset/NER/SympTEMIST/test/brat" # Carpeta que contiene los archivos de texto y anotaciones de test
  processed:
    train: "dataset/NER/SympTEMIST/processed/train/train.hf" # HF Dataset con los datos de train
    dev: "dataset/NER/SympTEMIST/processed/dev/dev.hf" # HF Dataset con los datos de dev
    test: "dataset/NER/SympTEMIST/processed/test/test.hf" # HF Dataset con los datos de test
  label_map: "dataset/NER/SympTEMIST/label_map/label2id.json"
  results: "results/NER/SympTEMIST/"
  model_dir: "models/NER/SympTEMIST/"

wandb_project: "eriberta-ner-SympTEMIST"

hyperparameters:
  batch_size: 8
  learning_rate: 2.0e-5
  weight_decay: 0.01