paths:
  raw:
    train: "datasets/NER/MEDDOPROF/subtrack2-class/train/brat" # Carpeta que contiene los archivos de texto y anotaciones de train
    dev: "datasets/NER/MEDDOPROF/subtrack2-class/dev/brat" # Carpeta que contiene los archivos de texto y anotaciones de dev
    test: "datasets/NER/MEDDOPROF/subtrack2-class/test/brat" # Carpeta que contiene los archivos de texto y anotaciones de test
  processed:
    train: "datasets/NER/MEDDOPROF/subtrack2-class/processed/train/train.hf" # HF Dataset con los datos de train
    dev: "datasets/NER/MEDDOPROF/subtrack2-class/processed/dev/dev.hf" # HF Dataset con los datos de dev
    test: "datasets/NER/MEDDOPROF/subtrack2-class/processed/test/test.hf" # HF Dataset con los datos de test
  label_map: "datasets/NER/MEDDOPROF/subtrack2-class/label_map/label2id.json"

models:
  eriberta:
    results: "results/eriberta/NER/MEDDOPROF/subtrack2-class/"
    model_name: "HiTZ/EriBERTa-base"
    wandb_project: "eriberta-ner-MEDDOPROF-subtrack2-class"
    hyperparameters:
      batch_size: 32
      learning_rate: 7.5e-5
      weight_decay: 0.0