paths:
  raw:
    train: "datasets/NER/MedProcNER/train/brat" # Carpeta que contiene los archivos de texto y anotaciones de train
    dev: "datasets/NER/MedProcNER/dev/brat" # Carpeta que contiene los archivos de texto y anotaciones de dev
    test: "datasets/NER/MedProcNER/test/brat" # Carpeta que contiene los archivos de texto y anotaciones de test
  processed:
    train: "datasets/NER/MedProcNER/processed/train/train.hf" # HF Dataset con los datos de train
    dev: "datasets/NER/MedProcNER/processed/dev/dev.hf" # HF Dataset con los datos de dev
    test: "datasets/NER/MedProcNER/processed/test/test.hf" # HF Dataset con los datos de test
  label_map: "datasets/NER/MedProcNER/label_map/label2id.json"

models:
  eriberta:
    results: "results/eriberta/NER/MedProcNER/"
    model_name: "HiTZ/EriBERTa-base"
    wandb_project: "eriberta-ner-MedProcNER"
    hyperparameters:
      batch_size: 16
      learning_rate: 5.0e-5
      weight_decay: 0.2

  eriberta_private:
    results: "results/eriberta/private/MedProcNER/"
    model_name: "eriberta_models/private/eriberta"
    wandb_project: "eriberta-private-MedProcNER"
    hyperparameters:
      batch_size: 16
      learning_rate: 5.0e-5
      weight_decay: 0.2

  longformer:
    results: "results/eriberta_longformer/public/MedProcNER/"
    model_name: "eriberta_models/public/EriBERTa_Free_longformer_1024_attn_2048_max_size"
    wandb_project: "eriberta_longformer-public-MedProcNER"
    hyperparameters: # TODO
      batch_size: 8
      learning_rate: 1.0e-5
      weight_decay: 0.0

  bsc:
    results: "results/bsc/public/MedProcNER/"
    model_name: "PlanTL-GOB-ES/bsc-bio-ehr-es"
    wandb_project: "bsc-public-MedProcNER"
    hyperparameters:
      batch_size: 16
      learning_rate: 7.5e-5
      weight_decay: 0.1