paths:
  raw:
    train: "datasets/NER/DisTEMIST/train/brat" # Carpeta que contiene los archivos de texto y anotaciones de train
    dev: "datasets/NER/DisTEMIST/dev/brat" # Carpeta que contiene los archivos de texto y anotaciones de dev
    test: "datasets/NER/DisTEMIST/test/brat" # Carpeta que contiene los archivos de texto y anotaciones de test
  processed:
    train: "datasets/NER/DisTEMIST/processed/train/train.hf" # HF Dataset con los datos de train
    dev: "datasets/NER/DisTEMIST/processed/dev/dev.hf" # HF Dataset con los datos de dev
    test: "datasets/NER/DisTEMIST/processed/test/test.hf" # HF Dataset con los datos de test
  label_map: "datasets/NER/DisTEMIST/label_map/label2id.json"

models:
  eriberta:
    results: "results/eriberta/NER/DisTEMIST/"
    model_name: "HiTZ/EriBERTa-base"
    wandb_project: "eriberta-ner-DisTEMIST"
    hyperparameters:
      batch_size: 8
      learning_rate: 5.0e-5
      weight_decay: 0.3

  eriberta_private:
    results: "results/eriberta/private/DisTEMIST/"
    model_name: "eriberta_models/private/eriberta"
    wandb_project: "eriberta-private-DisTEMIST"
    hyperparameters:
      batch_size: 8
      learning_rate: 5.0e-5
      weight_decay: 0.3
      
  longformer:
    results: "results/eriberta_longformer/public/DisTEMIST/"
    model_name: "eriberta_models/public/EriBERTa_Free_longformer_512_attn_4096_max_size-1_epoch"
    wandb_project: "eriberta_longformer-public-DisTEMIST"
    hyperparameters: # TODO
      batch_size: 8
      learning_rate: 1.0e-5
      weight_decay: 0.0

  bsc:
    results: "results/bsc/public/DisTEMIST/"
    model_name: "PlanTL-GOB-ES/bsc-bio-ehr-es"
    wandb_project: "bsc-public-DisTEMIST"
    hyperparameters:
      batch_size: 8
      learning_rate: 7.5e-5
      weight_decay: 0.01

  clin_x_es:
    results: "results/clin_x_es/public/DisTEMIST/"
    model_name: "llange/xlm-roberta-large-spanish-clinical"
    wandb_project: "clin_x_es-public-DisTEMIST"
    hyperparameters:
      batch_size: 8
      learning_rate: 7.5e-5
      weight_decay: 0.0

  mdeberta:
    results: "results/mdeberta/public/DisTEMIST/"
    model_name: "microsoft/mdeberta-v3-base"
    wandb_project: "mdeberta-public-DisTEMIST"
    hyperparameters:
      batch_size: 8
      learning_rate: 7.5e-5
      weight_decay: 0.01