paths:
  raw:
    train: "datasets/NER/MultiCardioNER/track2/es/train/brat" # Carpeta que contiene los archivos de texto y anotaciones de train
    dev: "datasets/NER/MultiCardioNER/track2/es/dev/brat" # Carpeta que contiene los archivos de texto y anotaciones de dev
    test: "datasets/NER/MultiCardioNER/track2/es/test/brat" # Carpeta que contiene los archivos de texto y anotaciones de test
  processed:
    train: "datasets/NER/MultiCardioNER/track2/es/processed/train/train.hf" # HF Dataset con los datos de train
    dev: "datasets/NER/MultiCardioNER/track2/es/processed/dev/dev.hf" # HF Dataset con los datos de dev
    test: "datasets/NER/MultiCardioNER/track2/es/processed/test/test.hf" # HF Dataset con los datos de test
  label_map: "datasets/NER/MultiCardioNER/track2/es/label_map/label2id.json"

models:
  eriberta:
    results: "results/eriberta/NER/MultiCardioNER/track2/es/"
    model_name: "HiTZ/EriBERTa-base"
    wandb_project: "eriberta-ner-MultiCardioNER-track2"
    hyperparameters:
      batch_size: 8
      learning_rate: 3.0e-5
      weight_decay: 0.01

  eriberta_private:
    results: "results/eriberta/private/MultiCardioNER/track2/es/"
    model_name: "eriberta_models/private/eriberta"
    wandb_project: "eriberta-private-MultiCardioNER-track2"
    hyperparameters:
      batch_size: 8
      learning_rate: 3.0e-5
      weight_decay: 0.01

  longformer:
    results: "results/eriberta_longformer/public/MultiCardioNER/track2/"
    model_name: "eriberta_models/public/EriBERTa_Free_longformer_512_attn_4096_max_size-1_epoch"
    wandb_project: "eriberta_longformer-public-MultiCardioNER-track2"
    hyperparameters: # TODO
      batch_size: 8
      learning_rate: 1.0e-5
      weight_decay: 0.0

  bsc:
    results: "results/bsc/public/MultiCardioNER/track2/"
    model_name: "PlanTL-GOB-ES/bsc-bio-ehr-es"
    wandb_project: "bsc-public-MultiCardioNER-track2"
    hyperparameters:
      batch_size: 8
      learning_rate: 3.0e-5
      weight_decay: 0.01

  clin_x_es:
    results: "results/clin_x_es/public/MultiCardioNER/track2/"
    model_name: "llange/xlm-roberta-large-spanish-clinical"
    wandb_project: "clin_x_es-public-MultiCardioNER-track2"
    hyperparameters:
      batch_size: 8
      learning_rate: 2.0e-5
      weight_decay: 0.3

  mdeberta:
    results: "results/mdeberta/public/MultiCardioNER/track2/"
    model_name: "microsoft/mdeberta-v3-base"
    wandb_project: "mdeberta-public-MultiCardioNER-track2"
    hyperparameters:
      batch_size: 8
      learning_rate: 2.0e-5
      weight_decay: 0.3