paths:
  raw:
    train: "dataset/NER/MultiCardioNER/track1/distemist_train/brat" # Carpeta que contiene los archivos de texto y anotaciones de train
    dev: "dataset/NER/MultiCardioNER/track1/cardiocc_dev/brat" # Carpeta que contiene los archivos de texto y anotaciones de dev
    test: "dataset/NER/MultiCardioNER/track1/cardiocc_test/brat" # Carpeta que contiene los archivos de texto y anotaciones de test
  processed:
    train: "dataset/NER/MultiCardioNER/track1/processed/train/train.hf" # HF Dataset con los datos de train
    dev: "dataset/NER/MultiCardioNER/track1/processed/dev/dev.hf" # HF Dataset con los datos de dev
    test: "dataset/NER/MultiCardioNER/track1/processed/test/test.hf" # HF Dataset con los datos de test
  label_map: "dataset/NER/MultiCardioNER/track1/label_map/label2id.json"
  results: "results/NER/MultiCardioNER/track1/"
  model_dir: "models/NER/MultiCardioNER/track1/"

wandb_project: "eriberta-ner-MultiCardioNER-track1"

hyperparameters:
  batch_size: 8
  learning_rate: 2.0e-5
  weight_decay: 0.01