paths:
  raw:
    train: "datasets/NER/EXPLORACION_FISICA_GENERAL/train" # Carpeta que contiene los archivos de texto y anotaciones de train
    dev: "datasets/NER/EXPLORACION_FISICA_GENERAL/dev" # Carpeta que contiene los archivos de texto y anotaciones de dev
    test: "datasets/NER/EXPLORACION_FISICA_GENERAL/test" # Carpeta que contiene los archivos de texto y anotaciones de test
  processed:
    train: "datasets/NER/EXPLORACION_FISICA_GENERAL/train/train.hf" # HF Dataset con los datos de train
    dev: "datasets/NER/EXPLORACION_FISICA_GENERAL/dev/dev.hf" # HF Dataset con los datos de dev
    test: "datasets/NER/EXPLORACION_FISICA_GENERAL/test/test.hf" # HF Dataset con los datos de test
  label_map: "datasets/NER/EXPLORACION_FISICA_GENERAL/label_map/label2id.json"

models:
  eriberta:
    results: "results/eriberta/NER/EXPLORACION_FISICA_GENERAL/"
    model_name: "HiTZ/EriBERTa-base"
    wandb_project: "eriberta-ner-EXPLORACION_FISICA_GENERAL"
    hyperparameters:
      batch_size: 16
      learning_rate: 3.0e-5
      weight_decay: 0.2

  eriberta_private:
    results: "results/eriberta/private/EXPLORACION_FISICA_GENERAL/"
    model_name: "eriberta_models/private/eriberta"
    wandb_project: "eriberta-private-EXPLORACION_FISICA_GENERAL"
    hyperparameters:
      batch_size: 8
      learning_rate: 5.0e-5
      weight_decay: 0.01
      
  longformer:
    results: "results/eriberta_longformer_512_attn_4096_max_size_global_attn/public/EXPLORACION_FISICA_GENERAL/"
    model_name: "eriberta_models/public/EriBERTa_Free_longformer_512_attn_4096_max_size-1_epoch"
    wandb_project: "eriberta_longformer-public-EXPLORACION_FISICA_GENERAL"
    hyperparameters:
      batch_size: 8
      learning_rate: 5.0e-5
      weight_decay: 0.01

  bsc:
    results: "results/bsc/public/EXPLORACION_FISICA_GENERAL/"
    model_name: "PlanTL-GOB-ES/bsc-bio-ehr-es"
    wandb_project: "bsc-public-EXPLORACION_FISICA_GENERAL"
    hyperparameters:
      batch_size: 8
      learning_rate: 5.0e-5
      weight_decay: 0.2

  clin_x_es:
    results: "results/clin_x_es/public/EXPLORACION_FISICA_GENERAL/"
    model_name: "llange/xlm-roberta-large-spanish-clinical"
    wandb_project: "clin_x_es-public-EXPLORACION_FISICA_GENERAL"
    hyperparameters:
      batch_size: 32
      learning_rate: 5.0e-5
      weight_decay: 0.1

  mdeberta:
    results: "results/mdeberta/public/EXPLORACION_FISICA_GENERAL/"
    model_name: "microsoft/mdeberta-v3-base"
    wandb_project: "mdeberta-public-EXPLORACION_FISICA_GENERAL"
    hyperparameters:
      batch_size: 8
      learning_rate: 5.0e-5
      weight_decay: 0.0