paths:
  raw:
    train: "datasets/NER/PharmacoNER/Sentences/train/brat" # Carpeta que contiene los archivos de texto y anotaciones de train
    dev: "datasets/NER/PharmacoNER/Sentences/dev/brat" # Carpeta que contiene los archivos de texto y anotaciones de dev
    test: "datasets/NER/PharmacoNER/Sentences/test/brat" # Carpeta que contiene los archivos de texto y anotaciones de test
  processed:
    train: "datasets/NER/PharmacoNER/Sentences/processed/train/train.hf" # HF Dataset con los datos de train
    dev: "datasets/NER/PharmacoNER/Sentences/processed/dev/dev.hf" # HF Dataset con los datos de dev
    test: "datasets/NER/PharmacoNER/Sentences/processed/test/test.hf" # HF Dataset con los datos de test
  label_map: "datasets/NER/PharmacoNER/Sentences/label_map/label2id.json"

models:
  eriberta:
    results: "results/eriberta/NER/PharmacoNER/Sentences/"
    model_name: "HiTZ/EriBERTa-base"
    wandb_project: "eriberta-ner-PharmacoNER-Sentences"
    hyperparameters:
      batch_size: 8
      learning_rate: 3.0e-5
      weight_decay: 0.0

  eriberta_private:
    results: "results/eriberta/private/PharmacoNER/Sentences/"
    model_name: "eriberta_models/private/eriberta"
    wandb_project: "eriberta-private-PharmacoNER-Sentences"
    hyperparameters:
      batch_size: 8
      learning_rate: 3.0e-5
      weight_decay: 0.0

  longformer:
    results: "results/eriberta_longformer/public/PharmacoNER/Sentences/"
    model_name: "eriberta_models/public/EriBERTa_Free_longformer_1024_attn_2048_max_size"
    wandb_project: "eriberta_longformer-public-PharmacoNER-Sentences"
    hyperparameters: # TODO
      batch_size: 8
      learning_rate: 1.0e-5
      weight_decay: 0.0

  bsc:
    results: "results/bsc/public/PharmacoNER/Sentences/"
    model_name: "PlanTL-GOB-ES/bsc-bio-ehr-es"
    wandb_project: "bsc-public-PharmacoNER-Sentences"
    hyperparameters:
      batch_size: 16
      learning_rate: 5.0e-5
      weight_decay: 0.2

  clin_x_es:
    results: "results/clin_x_es/public/PharmacoNER/Sentences/"
    model_name: "llange/xlm-roberta-large-spanish-clinical"
    wandb_project: "clin_x_es-public-PharmacoNER-Sentences"
    hyperparameters:
      batch_size: 16
      learning_rate: 3.0e-5
      weight_decay: 0.2

  mdeberta:
    results: "results/mdeberta/public/PharmacoNER/Sentences/"
    model_name: "microsoft/mdeberta-v3-base"
    wandb_project: "mdeberta-public-PharmacoNER-Sentences"
    hyperparameters:
      batch_size: 16
      learning_rate: 7.5e-5
      weight_decay: 0.3