paths:
  ner:
    raw:
      train: "data/ner/raw/train/" # Carpeta que contiene los archivos de texto y anotaciones de train
      dev: "data/ner/raw/dev/" # Carpeta que contiene los archivos de texto y anotaciones de dev
    processed:
      train: "data/ner/processed/train/train.hf" # HF Dataset con los datos de train
      dev: "data/ner/processed/dev/dev.hf" #  HF Dataset con los datos de dev
    model_dir: "models/ner/"
