paths:
  raw:
    train: "data/pharmaconer_ner/raw/train/" # Carpeta que contiene los archivos de texto y anotaciones de train
    dev: "data/pharmaconer_ner/raw/dev/" # Carpeta que contiene los archivos de texto y anotaciones de dev
    #test: "data/pharmaconer_ner/raw/test/"
  processed:
    train: "data/pharmaconer_ner/processed/train/train.hf" # HF Dataset con los datos de train
    dev: "data/pharmaconer_ner/processed/dev/dev.hf" # HF Dataset con los datos de dev
    #test: "data/pharmaconer_ner/processed/test/test.hf"
  label_map: "data/pharmaconer_ner/label_map/label2id.json"
  results: "results/pharmaconer_ner"
  model_dir: "models/pharmaconer_ner/"

wandb_project: "eriberta-pharmaconer_ner"

hyperparameters:
  batch_size: 8
  learning_rate: 2.0e-5
  weight_decay: 0.01