paths:
  raw:
    train: "datasets/NER/DisTEMIST/train/brat" # Carpeta que contiene los archivos de texto y anotaciones de train
    dev: "datasets/NER/DisTEMIST/dev/brat" # Carpeta que contiene los archivos de texto y anotaciones de dev
    test: "datasets/NER/DisTEMIST/test/brat" # Carpeta que contiene los archivos de texto y anotaciones de test
  processed:
    train: "datasets/NER/DisTEMIST/processed/train/train.hf" # HF Dataset con los datos de train
    dev: "datasets/NER/DisTEMIST/processed/dev/dev.hf" # HF Dataset con los datos de dev
    test: "datasets/NER/DisTEMIST/processed/test/test.hf" # HF Dataset con los datos de test
  label_map: "datasets/NER/DisTEMIST/label_map/label2id.json"

models:
  eriberta:
    results: "results/eriberta/NER/DisTEMIST/"
    model_name: "HiTZ/EriBERTa-base"
    wandb_project: "eriberta-ner-DisTEMIST"
    hyperparameters:
      batch_size: 8
      learning_rate: 5.0e-5
      weight_decay: 0.3